#!/bin/sh

### BEGIN INIT INFO
# Required-Start:    $local_fs $remote_fs $network $time
# Required-Stop:     $local_fs $remote_fs $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Initscript for netconsole under Debian
# Description:       Automatically configure netconsole at boot time
### END INIT INFO

export LANG=C
. /lib/lsb/init-functions


define_opts ()
{
    # sets $opts

    local route dev itf next_hop next_hop_mac src_ip src_mac dest_ip
    local src_port=6666
    local dest_port=514
    local dest_host=netconsole

    dest_ip=$(getent hosts $dest_host | cut -d' ' -f1)

    route=$(ip -o route get to $dest_ip/32)
    dev=$(echo $route | sed "s|.* dev \([^ ]*\).*|\1|")
    src_ip=$(echo $route | sed "s|.* src \([^ ]*\).*|\1|")

    itf=$(ip -o link show $dev)
    src_mac=$(echo $itf|sed "s|.* link/ether \([^ ]*\).*|\1|")

    next_hop=$dest_ip
    if echo $route | grep -q " via " ; then
        next_hop=$(echo $route | sed "s|.* via \([^ ]*\).*|\1|")
    fi

    # get the dest_mac
    ping -c1 -w10 $next_hop >/dev/null 2>&1
    if [ $? -ne 0 ]; then
        log_failure_msg "no ICMP reply from next hop"
        exit 1
    fi
    next_hop_mac=$(ip neighbour show $next_hop | \
        sed "s|.* lladdr \([^ ]*\).*|\1|")

    opts="netconsole=$src_port@$src_ip/$dev,$dest_port@$dest_ip/$next_hop_mac"
}

/sbin/lsmod | grep netconsole >/dev/null 2>&1
running=$?

start () {
    if [ $running -ne 0 ]; then
        define_opts
        modprobe netconsole $opts
        exit 0
    else
        log_warning_msg "already started"
        exit 1
    fi
}

stop () {
    if [ $running -eq 0 ]; then
        rmmod netconsole
        exit 0
    else
        log_warning_msg "not started"
        exit 1
    fi
}

# Return codes from http://refspecs.freestandards.org/LSB_3.1.0/LSB-Core-generic/LSB-Core-generic/iniscrptact.html
status () {
    if [ $running -eq 0 ]; then
        log_success_msg "netconsole is running"
        exit 0
    else
        log_failure_msg "netconsole is not running"
        exit 3
    fi
}



case "$1" in
    start)
        start;;
    stop)
        stop;;
    restart)
        stop
        start;;
    status)
        status;;
    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac
